
# Gem::Specification for Populator-0.1.0
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{populator}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bates"]
  s.date = %q{2008-08-27}
  s.description = %q{Mass populate an Active Record database.}
  s.email = %q{ryan (at) railscasts (dot) com}
  s.extra_rdoc_files = ["CHANGELOG", "lib/populator.rb", "LICENSE", "README", "tasks/deployment.rake", "tasks/spec.rake", "TODO"]
  s.files = ["CHANGELOG", "lib/populator.rb", "LICENSE", "Manifest", "README", "spec/models/product.rb", "spec/populator_spec.rb", "spec/spec_helper.rb", "spec/test.sqlite3", "tasks/deployment.rake", "tasks/spec.rake", "TODO", "populator.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/ryanb/populator}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Populator", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{populator}
  s.rubygems_version = %q{1.2.0}
  s.summary = %q{Mass populate an Active Record database.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if current_version >= 3 then
    else
    end
  else
  end
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'rake'
# require 'echoe'
# 
# Echoe.new('populator', '0.1.0') do |p|
#   p.summary        = "Mass populate an Active Record database."
#   p.description    = "Mass populate an Active Record database."
#   p.url            = "http://github.com/ryanb/populator"
#   p.author         = 'Ryan Bates'
#   p.email          = "ryan (at) railscasts (dot) com"
#   p.ignore_pattern = ["script/*"]
# end
# 
# Dir["#{File.dirname(__FILE__)}/tasks/*.rake"].sort.each { |ext| load ext }
