#!/usr/bin/env ruby
if ARGV.empty?
  $stderr.puts "Usage: ./script/profiler [times] 'Person.expensive_method(10)'"
  exit(1)
end

# load the spec_helper file even though this isn't necessarily for specs
# it's just a convenient, quick way to load all the requirements.
require File.dirname(__FILE__) + '/../spec/spec_helper'

repeat = ARGV.first.to_i > 1 ? ARGV.shift.to_i : 1
snippet = ARGV.shift

# Define a method to profile.
eval "def profile_me() #{repeat}.times { #{snippet} } end"

# Ensure we're running on a clean database
[Product, Category].each(&:delete_all)

require "ruby-prof"
RubyProf.measure_mode = RubyProf::WALL_TIME
RubyProf.start
profile_me
printer = RubyProf::GraphHtmlPrinter.new(RubyProf.stop)

Dir.mkdir('tmp') unless File.exist? 'tmp'
File.open('tmp/profile.html', 'w') do |file|
  printer.print(file)
end
`open tmp/profile.html &`
